# Generated by Django 3.2.5 on 2023-06-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_detail_url', models.URLField(default='#', verbose_name='详情页链接')),
                ('news_title', models.CharField(max_length=200, verbose_name='新闻标题')),
                ('news_tip', models.CharField(max_length=200, verbose_name='文章摘要')),
                ('image_url', models.ImageField(upload_to='', verbose_name='图片路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '新闻列表页',
                'verbose_name_plural': '新闻列表页',
                'db_table': 'news',
            },
        ),
    ]
