# Generated by Django 3.2.5 on 2023-06-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('project_desc', models.TextField(default='项目描述', max_length=300, verbose_name='项目描述')),
            ],
            options={
                'verbose_name': '项目表',
                'verbose_name_plural': '项目表',
                'db_table': 'projects',
            },
        ),
    ]
