# Generated by Django 3.2.5 on 2023-06-23 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False, verbose_name='项目ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images/', verbose_name='项目展示图片')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('desc', models.TextField(verbose_name='项目介绍')),
                ('tags', models.CharField(choices=[('tag1', 'AI教育'), ('tag2', 'AI绘画'), ('tag3', 'AI医疗'), ('tag4', 'AI金融'), ('tag5', 'AI游戏'), ('tag6', 'AI音乐'), ('tag7', 'AI翻译'), ('tag8', 'AI法律'), ('tag9', 'AI其他')], max_length=10, verbose_name='项目标签')),
                ('type', models.CharField(choices=[('type1', '学习型'), ('type2', '实践型')], max_length=10, verbose_name='项目类型')),
                ('status', models.CharField(choices=[('status1', '招募中'), ('status2', '开发中'), ('status3', '已完成')], max_length=10, verbose_name='项目状态')),
                ('cycles', models.IntegerField(blank=True, null=True, verbose_name='开发周期')),
                ('link', models.URLField(blank=True, null=True, verbose_name='项目地址')),
                ('views', models.IntegerField(default=0, verbose_name='浏览数量')),
                ('likes', models.IntegerField(default=0, verbose_name='点赞数量')),
                ('favorites', models.IntegerField(default=0, verbose_name='收藏数量')),
                ('other_info', models.TextField(blank=True, verbose_name='备注信息')),
                ('post_datetime', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('is_Active', models.BooleanField(default=True, verbose_name='招募状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'project',
            },
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
