# Generated by Django 3.2.5 on 2023-06-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20230624_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('招募中', '招募中'), ('开发中', '开发中'), ('已完成', '已完成')], max_length=10, verbose_name='项目状态'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.CharField(choices=[('AI教育', 'AI教育'), ('AI绘画', 'AI绘画'), ('AI医疗', 'AI医疗'), ('AI金融', 'AI金融'), ('AI游戏', 'AI游戏'), ('AI音乐', 'AI音乐'), ('AI翻译', 'AI翻译'), ('AI法律', 'AI法律'), ('AI其他', 'AI其他')], max_length=10, verbose_name='项目标签'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('学习型', '学习型'), ('实践型', '实践型')], max_length=10, verbose_name='项目类型'),
        ),
    ]
